### ISSUE TITLE
Any chance of adding rebinding chat key support for Valheim Chat Tweaks?

### ISSUE THREAD

**Issue by nomad-software** [kenx00x/Mods#1]
Any chance of adding rebinding chat key support for Valheim Chat Tweaks?

I would like to rebind the chat key to anything other than Enter.

Thanks.

**Comment by kenx00x** [comment]
I'll look into it. Sorry for the late response, I was taking a break from coding after my exams in school.

**Comment by kenx00x** [comment]
I added this

**Comment by nomad-software** [comment]
Great, thanks a lot! :smile:

**Comment by nomad-software** [comment]
After installing the mod, how do I change the binding? I can't seem to find any readme on how to use it.

**Comment by kenx00x** [comment]
you can either do one of these things:
-install configuration manager for bepinex and press f1 to change the config file (recommended way) (https://github.com/BepInEx/BepInEx.ConfigurationManager)
-go to Valheim\BepInEx\config\kenx00x.ChatTweaks.cfg and edit the chatkey

**Comment by nomad-software** [comment]
Cool, thanks!
