### ISSUE TITLE
I'm confused can someone help me install the BTD6 mods?

### ISSUE THREAD

**Issue by distributer-on-discord** [kenx00x/Mods#3]
I've got melon loader but there's no normal download button or .dll file like there usually is, what do I do to download and install the mods to my BTD6? (I've installed mods before I have a good bit I'm just confused on these specifically)

**Comment by kenx00x** [comment]
this is the source code, you can compile it yourself or you can download the mods from nexusmods https://www.nexusmods.com/bloonstd6/users/19587064?tab=user+files
